Added templates for Complaint, Mess, Leave, and Placement Modules
3Peers/FusionIIIT pull request #41
Opened 2017-10-16 18:23 UTC by kmunshi97

2017-10-16 18:26 UTC, arshadsid commented
Isort and flake8?

2017-10-16 18:28 UTC, Samy-33 commented
travis check has failed.  
I hope there is no unnecessary static file?

2017-10-16 19:01 UTC, arshadsid requested changes
Db name is incorrect in settings.py

2017-10-16 19:01 UTC, arshadsid commented on FusionIIIT/Fusion/settings.py
> +            'NAME': 'Fusion',
Db name is fusion.

2017-10-17 03:40 UTC, Samy-33 commented
@arshadsid and @pranjulps3 , please review this PR.

2017-10-17 09:11 UTC, merged